name: Publish Image to Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish_image:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate current date and image name
        id: image_name
        run: |
          IMAGE_NAME="localhost:5000/shlomi-$(date +'%Y-%m-%d-%H-%M-%S')"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo $IMAGE_NAME > image.txt

      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push image to local registry
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Commit updated image.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add image.txt
          git commit -m "Update image.txt with new image name"
          git push
