name: publish image to docker
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      -name: checkout
      uses:actions/checkout@v4
      -name: build image
       run: docker build /home/ta/flask-examples -t localhost:8082/shlomi
      -name: push image to local registry
       run:
         docker push localhost:8082/shlomi
